services:
  ##########################
  # ZABBIX AGENT 2
  ###########################
  zabbix-agent2:
    image: zabbix/zabbix-agent2:ubuntu-7.4.3
    container_name: databus-zabbix-agent2
    restart: unless-stopped
    privileged: true
    group_add:
      - "${DOCKER_GID}"
    #    networks:
    #      net0:
    #        ipv4_address: ${ZBX_AGENT2_IP}
    #user: "1001:996"
    environment:
      - ZBX_SERVER_HOST=r4.siua.ac.cr
      - ZBX_ACTIVE_ALLOW=true
      #- ZBX_HOSTNAME=${ZBX_HOSTNAME}
      - ZBX_METADATA=docker-autoreg
      #- ZBX_HOSTINTERFACE=1:databus.siua.ac.cr:10050
    volumes:
      - /proc:/proc
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
